### ISSUE TITLE
Logging framework

### ISSUE THREAD

**Issue by krukru** [degordian/js-coding-standards#11]
@bonzzy pointed out this nice library for logging called https://www.npmjs.com/package/winston

We already started working on something similar https://github.com/degordian/ts-logger

Should we continue developing our in-house logger or roll with winston. Post opinions and experience if you used winston before

**Comment by vilimco** [comment]
I am completely fine with using winston :D

As @krukru said, it is everything we needed and more.

+1 for using it :)

**Comment by napravicukod** [comment]
I would go with winston.
I've seen @DAPowerPlay use it as well.
