### ISSUE TITLE
Spread operators

### ISSUE THREAD

**Issue by bonzzy** [degordian/js-coding-standards#27]
What do you think about spread operators? [Operators/Spread_syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)

Use it or lose it? 👍

**Comment by krukru** [comment]
Do we get any compile time checks with this? In the example you linked, what if sum changes it's signature - will compile fail?

**Comment by tonymrakovcic** [comment]
new shiny stuff is always good in my opinion :)
Maybe first glance readability goes down a little, but only if you don't use it regularly and you're not used to it, but so does anything new

**Comment by bonzzy** [comment]
@krukru If you change `sum` function, for example remove `z`, than sum will always be x+y only, no matter how many values are in `array`.

If you leave `sum` as it is, but spread array with only two values, than `z` will be undefined. That makes sense?

**Comment by vilimco** [comment]
I find it as a good approach if you are writing functions/methods that are accepting unlimited number of params. Before spread operator, you used `arguments` over which you don't have actual control.

If you are using TS, you will have to define type for array you are using from spread operator, so you are still safe with the way it is being used.

I would say it is completely ok to use for those cases, but please, don't use it with tuples 😅:
```js
function(...args: [string, number][]) {
   // some functionality
}
```

It's a 👍 from me.

**Comment by krukru** [comment]
This is great because TS lint (or TSC) will not allow you to use spread operator on methods that are not accepting `...args`.

**Comment by bonzzy** [comment]
Ok so you all agree to close this issue and use spread?

**Comment by jakagacic** [comment]
👍
