### ISSUE TITLE
PM2 config parameters

### ISSUE THREAD

**Issue by bonzzy** [degordian/js-coding-standards#3]
Going through some repositories I saw that we use on many places PM2 config parameters like `process.env.SOMETHING`. 
I see problem in this because I think that we shouldn't put any random stuff in PM2 configs and directly access it like that. Firstly PHPStorm won't be able to understand those parameters and which types are and we won't know if we wrote something wrong, so debugging is out.

My proposition is that we always have a class like `ProcessConfig.ts` with static parameters which describe PM2 config.

Something like:
```typescript
class ProcessConfig {
  static SOMETHING = process.env.SOMETHING;
}
```
Usage:
```typescript
class SomeClassUsingConfig {
  public someMethod() {
    let value = ProcessConfig.SOMETHING;
  }
}
```

What do you think about it? @degordian/team-developers

**Comment by vilimco** [comment]
I generally look at things from classes, put yourself into that perspective: would you consume anything that someone unfamiliar gives you? 
That is exactly the same thing that is going on here: pm2 is launching your code and giving it some parameters. From the perspective of your code, you should validate those inputs somehow and then return some config class/interface. That way you will have a clean entry to your code.

My proposition:
```js
class ConfigProvider{
   public getConfig() : ConfigClass {
       const config = new ConfigClass();
       //....
       // example of settings variable
       config.enumValue = this.validateEnumValue(process.env.SOMETHING);
       //....
       return config;
   }
}
```

I know that some of you will comment that is too much to do to validate input, but think about how clean input to your are and where they can fail if someone calls it with invalid input. I think that it is better to fail while in control than to fail unexpectedly.
